[tool.poetry]
name = "securedrop-dev-docs"
version = "0.1.0"
description = ""
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sphinx = "^7.2.6"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.3.0"
