[tool.poetry]
name = "securedrop-dev-docs"
version = "0.1.0"
description = ""
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^8.2.1"
sphinx-autobuild = "^2024.10.3"
sphinx-rtd-theme = "^3.0.2"
