[tool.poetry]
name = "securedrop-dev-docs"
version = "0.1.0"
description = ""
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^7.4.4"
sphinx-autobuild = "^2024.2.4"
sphinx-rtd-theme = "^2.0.0"
