blank_issues_enabled: false

contact_links:
  - name: Getting Support
    url: https://docs.securedrop.org/en/stable/getting_support.html
    about: Please see our documentation for support on using SecureDrop. 
