#!/bin/sh
#
# Run the docs build process, producing `build/latest` instead of
# `docs/_build`. Can be extended to also build `stable`.

set -e

do_build() {
    git checkout "$1"

    make html
    # Remote-loaded SVGs will cause a build failure unless we use force-mode.
    LATEXMKOPTS="-interaction=nonstopmode -f" make latexpdf || true

    mkdir -p build
    mv docs/_build "build/${2}"
}

export SECUREDROP_DOCS_RELEASE=latest
do_build "$1" latest
