#!/bin/sh
#
# Run the docs build process, producing `build/latest` instead of
# `docs/_build`. Can be extended to also build `stable`.

set -e

do_build() {
    git checkout "$1"

    make html
    # Concatenate every page into one HTML file, then have headless Chromium
    # print it to PDF. This replaces the old LaTeX-based `make latexpdf`.
    make singlehtml
    chromium \
        --headless \
        --no-sandbox \
        --disable-gpu \
        --virtual-time-budget=120000 \
        --no-pdf-header-footer \
        --print-to-pdf=docs/_build/singlehtml/SecureDropDevDocs.pdf \
        "file://$(pwd)/docs/_build/singlehtml/index.html"

    mkdir -p build
    mv docs/_build "build/${2}"
}

export SECUREDROP_DOCS_RELEASE=latest
do_build "$1" latest
