---
name: CI

on: 
  merge_group: 
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  reusable:
    uses: freedomofpress/securedrop-docs/.github/workflows/ci.yml@main
