name: Link check
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make python3-pip
          pip install poetry==1.4.0
          poetry install --no-ansi
      - name: Run lint
        run: |
          make docs-linkcheck
