---
name: Link check

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  reusable:
    # TODO: switch back to main once securedrop-docs is on bookworm
    uses: freedomofpress/securedrop-docs/.github/workflows/linkcheck.yml@bookworm
